"""Creación inicial de tablas Wonka

Revision ID: 6fa76e342e10
Revises: 
Create Date: 2026-04-03 00:15:15.954030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa76e342e10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id_producto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('precio_venta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('costo_produccion_estimado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unidad_medida', sa.String(length=20), nullable=True),
    sa.Column('tiempo_produccion_minutos', sa.Integer(), nullable=True),
    sa.Column('receta', sa.String(length=200), nullable=True),
    sa.Column('imagen_producto', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_table('proveedores',
    sa.Column('id_proveedor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('contacto', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('ruc', sa.String(length=20), nullable=True),
    sa.Column('notas', sa.String(length=200), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id_proveedor')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('rol', sa.Enum('ADMIN', 'CLIENTE'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('clientes',
    sa.Column('id_cliente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('tipo', sa.Enum('MINORISTA', 'MAYORISTA'), nullable=True),
    sa.Column('fecha_registro', sa.Date(), nullable=True),
    sa.Column('categoria_comprador', sa.Enum('OCASIONAL', 'FRECUENTE'), nullable=True),
    sa.Column('imagen_cliente', sa.String(length=500), nullable=True),
    sa.Column('notas', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('materias_primas',
    sa.Column('id_materia_prima', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('unidad_medida', sa.String(length=20), nullable=False),
    sa.Column('stock_actual', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stock_minimo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('costo_unitario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('fecha_ultima_compra', sa.Date(), nullable=True),
    sa.Column('porcentaje_merma', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('imagen_materia', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id_proveedor'], ),
    sa.PrimaryKeyConstraint('id_materia_prima')
    )
    op.create_table('recetas',
    sa.Column('id_receta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('nombre_receta', sa.String(length=100), nullable=True),
    sa.Column('cantidad_lote', sa.Integer(), nullable=True),
    sa.Column('instrucciones', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_receta')
    )
    op.create_table('compras_materia_prima',
    sa.Column('id_compra', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('materia_prima_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_compra', sa.DateTime(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['materia_prima_id'], ['materias_primas.id_materia_prima'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id_proveedor'], ),
    sa.PrimaryKeyConstraint('id_compra')
    )
    op.create_table('ordenes_produccion',
    sa.Column('id_orden_produccion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_requerida', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'EN_PROCESO', 'COMPLETADA', 'CANCELADA'), nullable=True),
    sa.Column('lote', sa.String(length=50), nullable=True),
    sa.Column('prioridad', sa.Enum('BAJA', 'MEDIA', 'ALTA', 'URGENTE'), nullable=True),
    sa.Column('observaciones', sa.String(length=200), nullable=True),
    sa.Column('costo_total_real', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('receta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id_producto'], ),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id_receta'], ),
    sa.PrimaryKeyConstraint('id_orden_produccion'),
    sa.UniqueConstraint('lote')
    )
    op.create_table('recetas_detalle',
    sa.Column('id_receta_detalle', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('receta_id', sa.Integer(), nullable=False),
    sa.Column('materia_prima_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_necesaria', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['materia_prima_id'], ['materias_primas.id_materia_prima'], ),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id_receta'], ),
    sa.PrimaryKeyConstraint('id_receta_detalle')
    )
    op.create_table('ventas',
    sa.Column('id_venta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('fecha_venta', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('impuestos', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('descuento', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('metodo_pago', sa.Enum('EFECTIVO', 'TARJETA'), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'COMPLETADA', 'CANCELADA', 'DEVUELTA'), nullable=True),
    sa.Column('canal', sa.Enum('TIENDA', 'WEB', 'OTRA'), nullable=True),
    sa.Column('empleado', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.String(length=200), nullable=True),
    sa.Column('utilidad_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('costo_total_ventas', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_venta')
    )
    op.create_table('detalles_ventas',
    sa.Column('id_detalle', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('costo_unitario_momento_venta', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id_producto'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id_venta'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_table('pagos_proveedores',
    sa.Column('id_pago', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.Enum('EFECTIVO', 'TRANSFERENCIA'), nullable=True),
    sa.Column('compra_id', sa.Integer(), nullable=True),
    sa.Column('numero_comprobante', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.String(length=200), nullable=True),
    sa.Column('usuario_registro', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['compra_id'], ['compras_materia_prima.id_compra'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id_proveedor'], ),
    sa.PrimaryKeyConstraint('id_pago')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagos_proveedores')
    op.drop_table('detalles_ventas')
    op.drop_table('ventas')
    op.drop_table('recetas_detalle')
    op.drop_table('ordenes_produccion')
    op.drop_table('compras_materia_prima')
    op.drop_table('recetas')
    op.drop_table('materias_primas')
    op.drop_table('clientes')
    op.drop_table('usuarios')
    op.drop_table('proveedores')
    op.drop_table('productos')
    # ### end Alembic commands ###
